### ISSUE TITLE
README link is broken

### ISSUE THREAD

**Issue by Lorenzobattistela** [dntfindmel/python-player-pysimplegui#1]
The image above documentações is not showing. Source of the broken img: https://o.remove.bg/downloads/e3a9ab59-2c00-4edf-9e9d-4b6b5b7d4a45/png-clipart-venomous-snake-reptile-animal-snake-animals-cobra-removebg-preview.png"

![image](https://github.com/dntfindmel/python-player-pysimplegui/assets/70359945/39ab132d-1791-4580-9d53-90d4731a2220)

**Comment by dntfindmel** [comment]
Thank you! I already changed it, hope it dont break again lol 😊
